# 服务器, 默认端口9000,
# 如果提升端口已被占用, 请修改空闲的端口号再重新开始服务器和客户端

server_host: 127.0.0.1
server_port: 9203


# 当前支持llms的配置信息
llms: {
  chatglm3-6b: { 
    name: chatglm3-6b,
    host: 127.0.0.1,
    port: 8501
  },
}
